# Generated by Django 4.2.4 on 2023-08-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_message_conversation_alter_message_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
    ]
