# Generated by Django 4.2.4 on 2023-08-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_remove_message_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
