# Generated by Django 4.2.4 on 2023-08-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_title',
            field=models.TextField(default='My First Chat'),
        ),
    ]
