# Generated by Django 4.2.4 on 2023-08-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_conversation_chat_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registeredadmin',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
    ]
