# Generated by Django 4.2.4 on 2023-08-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_registeredadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredadmin',
            old_name='user_email',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='registeredadmin',
            old_name='user_id',
            new_name='admin_id',
        ),
        migrations.RenameField(
            model_name='registeredadmin',
            old_name='user_name',
            new_name='admin_name',
        ),
        migrations.RenameField(
            model_name='registeredadmin',
            old_name='user_password',
            new_name='admin_password',
        ),
    ]
