# Generated by Django 4.2.4 on 2023-08-31 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0011_rename_user_email_registeredadmin_admin_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registeredadmin',
            new_name='Admin',
        ),
    ]
